### ISSUE TITLE
Storage not working

### ISSUE THREAD

**Issue by morkeleb** [naskio/n8n-nodes-changed#1]
I keep getting true on changes even though there is no change.

**Comment by naskio** [comment]
`README.md`
> This node works only in trigger mode (with Cron, Webhook, etc.), in manual mode it will always use the default value.

**Comment by morkeleb** [comment]
Yes, it's not working in cron-mode 🙂
That is the issue.

**Comment by morkeleb** [comment]
I am as such getting an email every hour :)

**Comment by naskio** [comment]
You didn't provide enough data
It is working normally on my instance (n8n v0.179.0)
